### ISSUE TITLE
Create script for showing GitHub Copilot CLI functionality.

### ISSUE THREAD

**Issue by richross** [microsoft/MTC_GHCopilot_SB#18]
This feature is currently available in EXP using your TA persona (this core gorup only) or your EXP Developer persona.

This feature provides copilot access in the command line interface (CLI).  With this access, Copilot can suggest or explain commands for : 

- github cli 
- git
- the shell environment

**Comment by jdvcDev** [comment]
Complete in PR#19

https://github.com/microsoft/MTC_GHCopilot_SB/pull/19
